-- 1. Enable pgvector extension
create extension if not exists vector;

-- 2. Create table
create table if not exists research_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  file_path text,
  category text, 
  tags text[],
  embedding vector(768), 
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Security
alter table research_documents enable row level security;
create policy "Public documents are viewable by everyone" on research_documents for select using ( true );
create index if not exists research_docs_category_idx on research_documents(category);
