-- Create research_documents table
create table if not exists research_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  file_path text,
  category text, -- 'knowledge_base', 'raw_data', 'specs', etc.
  tags text[],
  embedding vector(768), -- For future semantic search with Gemini
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table research_documents enable row level security;

-- Policies (Viewable by everyone for now, writable only by service role)
create policy "Public documents are viewable by everyone"
  on research_documents for select hiding (embedding)
  using ( true );

-- Create index for faster search
create index if not exists research_docs_category_idx on research_documents(category);
