-- Topics Queue Table
create table if not exists topics (
  id bigint generated by default as identity primary key,
  title text not null,
  category text,
  status text default 'pending', -- pending, in_progress, researched, written, published
  priority int default 0,
  scraped_data jsonb, -- Store scraped research data
  generated_prompt text, -- Store generated Claude prompt
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Security
alter table topics enable row level security;
create policy "Topics are viewable by everyone" on topics for select using ( true );
create policy "Topics are editable by everyone" on topics for all using ( true );

-- Index for faster status queries
create index if not exists topics_status_idx on topics(status);
create index if not exists topics_priority_idx on topics(priority desc);
